### ISSUE TITLE
Create CI/CD

### ISSUE THREAD

**Issue by mateusluizfb** [mateusluizfb/crawley-ex#4]
Setup a CI/CD for this MIx project

**Comment by mateusluizfb** [comment]
Circle CI it's a good option :eyes:

**Comment by rodriggochaves** [comment]
Can I take this issue? I've a question about it.

1) Where we should deploy? There is a equivalent of https://rubygems.org to Elixir community?

**Comment by mateusluizfb** [comment]
Yes, you can deploy in https://hex.pm/

**Comment by rodriggochaves** [comment]
I need some informations from you:

1) a description of what this project is?
2) which license we going to use?

**Comment by mateusluizfb** [comment]
1. "Crawley is an elixir package that mine the Github API searching for repos to download and then zip and upload them to a S3 bucket."
